# Generated by Django 2.2.1 on 2019-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='1', max_length=50, verbose_name='书籍作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='1', max_length=50, verbose_name='类型'),
        ),
    ]
