# Generated by Django 2.2.1 on 2019-05-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类主键')),
                ('title', models.CharField(max_length=50, verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签主键')),
                ('title', models.CharField(max_length=30, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章主键')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('look_num', models.PositiveIntegerField(verbose_name='访问量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='文章分类')),
                ('tag', models.ManyToManyField(to='article.Tag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
